apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  namespace: clever-heisenberg
  name: clever-heisenberg-backend
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
