apiVersion: v1
kind: Service
metadata:
  namespace: clever-heisenberg
  labels:
    app: website
  name: website
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: website
