kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: clever-heisenberg
  name: website-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
