apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      nginx-ingress-default-backend'
  creationTimestamp: 2019-02-17T19:38:39Z
  generateName: nginx-nginx-ingress-default-backend-98bc48788-
  labels:
    app: nginx-ingress
    component: default-backend
    pod-template-hash: "546704344"
    release: nginx
  name: nginx-nginx-ingress-default-backend-98bc48788-66nqt
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-nginx-ingress-default-backend-98bc48788
    uid: 9ffb4983-32eb-11e9-b429-42010a840167
  resourceVersion: "729490"
  selfLink: /api/v1/namespaces/default/pods/nginx-nginx-ingress-default-backend-98bc48788-66nqt
  uid: a00512f3-32eb-11e9-b429-42010a840167
spec:
  containers:
  - image: k8s.gcr.io/defaultbackend:1.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: nginx-ingress-default-backend
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-qdc8c
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: gke-standard-cluster-1-default-pool-8fa049d3-vvxl
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-qdc8c
    secret:
      defaultMode: 420
      secretName: default-token-qdc8c
